### PR TITLE
Feature/add support for on commit actions

### PR DESCRIPTION
**Pull request by jackton1**
@mixxorz Any chance we could get this reviewed soon. Thanks

### CODE REVIEW

**Comment by jackton1** [comment]
Sure, would update it in a bit. Thanks

**Comment by jackton1** [comment]
@mixxorz Done.

**Comment by jackton1** [comment]
Should be updated

> Hey @jackton1 . Thanks for this. Sorry it's taken so long for me to see this.
> 
> I think overall this looks fine. Do you mind expanding in the docs a little bit about what `post_process` does? Other than that I think this can go in.

**Comment by mixxorz** [comment]
Awesome. Thanks @jackton1 . I'll prepare a new release as soon as I'm able.

**Pull request merged**
