### PR TITLE
Feature/optimized project imports

### PR DESCRIPTION
**Pull request by jackton1**

### CODE REVIEW

**Comment by mixxorz** [comment]
This LGTM. Thanks for tidying up! Like the other one, please rebase this so it's just one commit. Thanks. 😄

**Comment by jackton1** [comment]
@mixxorz No worries. Rebased with current master.

**Comment by mixxorz** [comment]
Sorry. I just merged in your other PR and there are conflicts. Oops.

**Comment by jackton1** [comment]
@mixxorz No worries. Resolved the conflicts.

**Pull request merged**
