### PR TITLE
Update service metaclass

### PR DESCRIPTION
**Pull request by jackton1**

### CODE REVIEW

**Comment by jackton1** [comment]
Changes from PR #20

**Comment by c17r** [comment]
Because you merged in some of your other branches, there was more than the single change in this PR.  I reset the branch to origin/master and then cherry-picked in the appropriate commits so the PR is about a singular change.

This fails because Django is tricky, `DeclarativeFieldsMetaclass` is derived from `MediaDefiningClass` which is where the error is being thrown.  I tried a couple of things to fix but meta programming isn't my forte.

We may have to leave it the way it is unless you've got some other ideas.

**Comment by jackton1** [comment]
@mixxorz, @c17r could you review th

**Comment by c17r** [comment]
Code looks good.  Can you rebase the branch from latest master?  That'll clear out the commits that aren't related to this change.  If not, I'll do it later tonight.

**Comment by c17r** [comment]
I'm not sure what happened with your rebase.  All it needed was to get latest master, switch to the feature branch, and then `git rebase master` and deal with any conflicts.  Should have taken like 10 minutes.

I reset the branch back to master and then cherry picked in the appropriate commits.

Everything is merged so you can kill the branch on your end.

Thanks for the feature!

**Pull request merged**
